/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IFundWalletInterface extends ethers.utils.Interface {
  functions: {
    "adaptor()": FunctionFragment;
    "billsTypedHash()": FunctionFragment;
    "ownerOf(address,bytes32)": FunctionFragment;
    "providers()": FunctionFragment;
    "recharge(address,uint64,bytes32,uint256,bytes)": FunctionFragment;
    "rechargeTypedHash()": FunctionFragment;
    "spend(address,uint64,bytes32,bytes,uint256,bytes)": FunctionFragment;
    "transferWalletOwner(address,bytes32,address)": FunctionFragment;
    "withdraw((address,uint64,bytes32,bytes,uint256),address,uint256,bytes)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "adaptor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "billsTypedHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "providers", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recharge",
    values: [string, BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rechargeTypedHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "spend",
    values: [
      string,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferWalletOwner",
    values: [string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [
      {
        provider: string;
        nonce: BigNumberish;
        account: BytesLike;
        bills: BytesLike;
        expiration: BigNumberish;
      },
      string,
      BigNumberish,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(functionFragment: "adaptor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "billsTypedHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "providers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recharge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rechargeTypedHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "spend", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferWalletOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "Billing(address,uint64,bytes32,bytes,uint256)": EventFragment;
    "BillsTypedHashUpdated(bytes32)": EventFragment;
    "NonceUpdated(address,bytes32,uint64,uint8)": EventFragment;
    "ProvidersUpdated(address)": EventFragment;
    "RechargeTypedHashUpdated(bytes32)": EventFragment;
    "Recharged(address,uint64,bytes32,uint256)": EventFragment;
    "ResourceAdaptorUpdated(address)": EventFragment;
    "Spent(address,uint64,bytes32,uint256)": EventFragment;
    "WalletOwnerTransferred(address,bytes32,address)": EventFragment;
    "Withdrawn(address,uint64,bytes32,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Billing"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BillsTypedHashUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NonceUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProvidersUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RechargeTypedHashUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Recharged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ResourceAdaptorUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Spent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WalletOwnerTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdrawn"): EventFragment;
}

export type BillingEvent = TypedEvent<
  [string, BigNumber, string, string, BigNumber] & {
    provider: string;
    nonce: BigNumber;
    account: string;
    bills: string;
    amount: BigNumber;
  }
>;

export type BillsTypedHashUpdatedEvent = TypedEvent<
  [string] & { hash: string }
>;

export type NonceUpdatedEvent = TypedEvent<
  [string, string, BigNumber, number] & {
    provider: string;
    account: string;
    nonce: BigNumber;
    purpose: number;
  }
>;

export type ProvidersUpdatedEvent = TypedEvent<
  [string] & { providers: string }
>;

export type RechargeTypedHashUpdatedEvent = TypedEvent<
  [string] & { hash: string }
>;

export type RechargedEvent = TypedEvent<
  [string, BigNumber, string, BigNumber] & {
    provider: string;
    nonce: BigNumber;
    account: string;
    amount: BigNumber;
  }
>;

export type ResourceAdaptorUpdatedEvent = TypedEvent<
  [string] & { adaptor: string }
>;

export type SpentEvent = TypedEvent<
  [string, BigNumber, string, BigNumber] & {
    provider: string;
    nonce: BigNumber;
    account: string;
    fee: BigNumber;
  }
>;

export type WalletOwnerTransferredEvent = TypedEvent<
  [string, string, string] & {
    provider: string;
    account: string;
    newOwner: string;
  }
>;

export type WithdrawnEvent = TypedEvent<
  [string, BigNumber, string, string, BigNumber] & {
    provider: string;
    nonce: BigNumber;
    account: string;
    to: string;
    amount: BigNumber;
  }
>;

export class IFundWallet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IFundWalletInterface;

  functions: {
    adaptor(overrides?: CallOverrides): Promise<[string]>;

    billsTypedHash(overrides?: CallOverrides): Promise<[string]>;

    ownerOf(
      provider: string,
      account: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    providers(overrides?: CallOverrides): Promise<[string]>;

    recharge(
      provider: string,
      nonce: BigNumberish,
      account: BytesLike,
      amount: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rechargeTypedHash(overrides?: CallOverrides): Promise<[string]>;

    spend(
      provider: string,
      nonce: BigNumberish,
      account: BytesLike,
      bills: BytesLike,
      expiration: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferWalletOwner(
      provider: string,
      account: BytesLike,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      payload: {
        provider: string;
        nonce: BigNumberish;
        account: BytesLike;
        bills: BytesLike;
        expiration: BigNumberish;
      },
      to: string,
      amount: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  adaptor(overrides?: CallOverrides): Promise<string>;

  billsTypedHash(overrides?: CallOverrides): Promise<string>;

  ownerOf(
    provider: string,
    account: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  providers(overrides?: CallOverrides): Promise<string>;

  recharge(
    provider: string,
    nonce: BigNumberish,
    account: BytesLike,
    amount: BigNumberish,
    signature: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rechargeTypedHash(overrides?: CallOverrides): Promise<string>;

  spend(
    provider: string,
    nonce: BigNumberish,
    account: BytesLike,
    bills: BytesLike,
    expiration: BigNumberish,
    signature: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferWalletOwner(
    provider: string,
    account: BytesLike,
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    payload: {
      provider: string;
      nonce: BigNumberish;
      account: BytesLike;
      bills: BytesLike;
      expiration: BigNumberish;
    },
    to: string,
    amount: BigNumberish,
    signature: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    adaptor(overrides?: CallOverrides): Promise<string>;

    billsTypedHash(overrides?: CallOverrides): Promise<string>;

    ownerOf(
      provider: string,
      account: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    providers(overrides?: CallOverrides): Promise<string>;

    recharge(
      provider: string,
      nonce: BigNumberish,
      account: BytesLike,
      amount: BigNumberish,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    rechargeTypedHash(overrides?: CallOverrides): Promise<string>;

    spend(
      provider: string,
      nonce: BigNumberish,
      account: BytesLike,
      bills: BytesLike,
      expiration: BigNumberish,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferWalletOwner(
      provider: string,
      account: BytesLike,
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      payload: {
        provider: string;
        nonce: BigNumberish;
        account: BytesLike;
        bills: BytesLike;
        expiration: BigNumberish;
      },
      to: string,
      amount: BigNumberish,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "Billing(address,uint64,bytes32,bytes,uint256)"(
      provider?: null,
      nonce?: null,
      account?: null,
      bills?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, string, string, BigNumber],
      {
        provider: string;
        nonce: BigNumber;
        account: string;
        bills: string;
        amount: BigNumber;
      }
    >;

    Billing(
      provider?: null,
      nonce?: null,
      account?: null,
      bills?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, string, string, BigNumber],
      {
        provider: string;
        nonce: BigNumber;
        account: string;
        bills: string;
        amount: BigNumber;
      }
    >;

    "BillsTypedHashUpdated(bytes32)"(
      hash?: null
    ): TypedEventFilter<[string], { hash: string }>;

    BillsTypedHashUpdated(
      hash?: null
    ): TypedEventFilter<[string], { hash: string }>;

    "NonceUpdated(address,bytes32,uint64,uint8)"(
      provider?: null,
      account?: null,
      nonce?: null,
      purpose?: null
    ): TypedEventFilter<
      [string, string, BigNumber, number],
      { provider: string; account: string; nonce: BigNumber; purpose: number }
    >;

    NonceUpdated(
      provider?: null,
      account?: null,
      nonce?: null,
      purpose?: null
    ): TypedEventFilter<
      [string, string, BigNumber, number],
      { provider: string; account: string; nonce: BigNumber; purpose: number }
    >;

    "ProvidersUpdated(address)"(
      providers?: null
    ): TypedEventFilter<[string], { providers: string }>;

    ProvidersUpdated(
      providers?: null
    ): TypedEventFilter<[string], { providers: string }>;

    "RechargeTypedHashUpdated(bytes32)"(
      hash?: null
    ): TypedEventFilter<[string], { hash: string }>;

    RechargeTypedHashUpdated(
      hash?: null
    ): TypedEventFilter<[string], { hash: string }>;

    "Recharged(address,uint64,bytes32,uint256)"(
      provider?: null,
      nonce?: null,
      account?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber],
      { provider: string; nonce: BigNumber; account: string; amount: BigNumber }
    >;

    Recharged(
      provider?: null,
      nonce?: null,
      account?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber],
      { provider: string; nonce: BigNumber; account: string; amount: BigNumber }
    >;

    "ResourceAdaptorUpdated(address)"(
      adaptor?: null
    ): TypedEventFilter<[string], { adaptor: string }>;

    ResourceAdaptorUpdated(
      adaptor?: null
    ): TypedEventFilter<[string], { adaptor: string }>;

    "Spent(address,uint64,bytes32,uint256)"(
      provider?: null,
      nonce?: null,
      account?: null,
      fee?: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber],
      { provider: string; nonce: BigNumber; account: string; fee: BigNumber }
    >;

    Spent(
      provider?: null,
      nonce?: null,
      account?: null,
      fee?: null
    ): TypedEventFilter<
      [string, BigNumber, string, BigNumber],
      { provider: string; nonce: BigNumber; account: string; fee: BigNumber }
    >;

    "WalletOwnerTransferred(address,bytes32,address)"(
      provider?: null,
      account?: null,
      newOwner?: null
    ): TypedEventFilter<
      [string, string, string],
      { provider: string; account: string; newOwner: string }
    >;

    WalletOwnerTransferred(
      provider?: null,
      account?: null,
      newOwner?: null
    ): TypedEventFilter<
      [string, string, string],
      { provider: string; account: string; newOwner: string }
    >;

    "Withdrawn(address,uint64,bytes32,address,uint256)"(
      provider?: null,
      nonce?: null,
      account?: null,
      to?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, string, string, BigNumber],
      {
        provider: string;
        nonce: BigNumber;
        account: string;
        to: string;
        amount: BigNumber;
      }
    >;

    Withdrawn(
      provider?: null,
      nonce?: null,
      account?: null,
      to?: null,
      amount?: null
    ): TypedEventFilter<
      [string, BigNumber, string, string, BigNumber],
      {
        provider: string;
        nonce: BigNumber;
        account: string;
        to: string;
        amount: BigNumber;
      }
    >;
  };

  estimateGas: {
    adaptor(overrides?: CallOverrides): Promise<BigNumber>;

    billsTypedHash(overrides?: CallOverrides): Promise<BigNumber>;

    ownerOf(
      provider: string,
      account: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    providers(overrides?: CallOverrides): Promise<BigNumber>;

    recharge(
      provider: string,
      nonce: BigNumberish,
      account: BytesLike,
      amount: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rechargeTypedHash(overrides?: CallOverrides): Promise<BigNumber>;

    spend(
      provider: string,
      nonce: BigNumberish,
      account: BytesLike,
      bills: BytesLike,
      expiration: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferWalletOwner(
      provider: string,
      account: BytesLike,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      payload: {
        provider: string;
        nonce: BigNumberish;
        account: BytesLike;
        bills: BytesLike;
        expiration: BigNumberish;
      },
      to: string,
      amount: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    adaptor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    billsTypedHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ownerOf(
      provider: string,
      account: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    providers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    recharge(
      provider: string,
      nonce: BigNumberish,
      account: BytesLike,
      amount: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rechargeTypedHash(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    spend(
      provider: string,
      nonce: BigNumberish,
      account: BytesLike,
      bills: BytesLike,
      expiration: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferWalletOwner(
      provider: string,
      account: BytesLike,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      payload: {
        provider: string;
        nonce: BigNumberish;
        account: BytesLike;
        bills: BytesLike;
        expiration: BigNumberish;
      },
      to: string,
      amount: BigNumberish,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
