/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IProvidersInterface extends ethers.utils.Interface {
  functions: {
    "isProvider(address)": FunctionFragment;
    "isValidSignature(address,bytes32,bytes)": FunctionFragment;
    "wallets(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "isProvider", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isValidSignature",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "wallets", values: [string]): string;

  decodeFunctionResult(functionFragment: "isProvider", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wallets", data: BytesLike): Result;

  events: {
    "ProviderUpdated(address,address)": EventFragment;
    "RemoveProvider(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ProviderUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemoveProvider"): EventFragment;
}

export type ProviderUpdatedEvent = TypedEvent<
  [string, string] & { provider: string; wallet: string }
>;

export type RemoveProviderEvent = TypedEvent<[string] & { provider: string }>;

export class IProviders extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IProvidersInterface;

  functions: {
    isProvider(provider: string, overrides?: CallOverrides): Promise<[boolean]>;

    isValidSignature(
      provider: string,
      hash: BytesLike,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    wallets(provider: string, overrides?: CallOverrides): Promise<[string]>;
  };

  isProvider(provider: string, overrides?: CallOverrides): Promise<boolean>;

  isValidSignature(
    provider: string,
    hash: BytesLike,
    signature: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  wallets(provider: string, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    isProvider(provider: string, overrides?: CallOverrides): Promise<boolean>;

    isValidSignature(
      provider: string,
      hash: BytesLike,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    wallets(provider: string, overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ProviderUpdated(address,address)"(
      provider?: null,
      wallet?: null
    ): TypedEventFilter<[string, string], { provider: string; wallet: string }>;

    ProviderUpdated(
      provider?: null,
      wallet?: null
    ): TypedEventFilter<[string, string], { provider: string; wallet: string }>;

    "RemoveProvider(address)"(
      provider?: null
    ): TypedEventFilter<[string], { provider: string }>;

    RemoveProvider(
      provider?: null
    ): TypedEventFilter<[string], { provider: string }>;
  };

  estimateGas: {
    isProvider(provider: string, overrides?: CallOverrides): Promise<BigNumber>;

    isValidSignature(
      provider: string,
      hash: BytesLike,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    wallets(provider: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    isProvider(
      provider: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidSignature(
      provider: string,
      hash: BytesLike,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    wallets(
      provider: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
