/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IDstChainPayment,
  IDstChainPaymentInterface,
} from "../IDstChainPayment";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "contract IERC20Upgradeable",
        name: "token",
        type: "address",
      },
      {
        components: [
          {
            internalType: "address",
            name: "provider",
            type: "address",
          },
          {
            internalType: "uint64",
            name: "nonce",
            type: "uint64",
          },
          {
            internalType: "bytes32",
            name: "account",
            type: "bytes32",
          },
          {
            components: [
              {
                internalType: "enum ResourceData.ResourceType",
                name: "resourceType",
                type: "uint8",
              },
              {
                internalType: "uint256[]",
                name: "values",
                type: "uint256[]",
              },
            ],
            internalType: "struct ResourceData.Payload[]",
            name: "payloads",
            type: "tuple[]",
          },
        ],
        indexed: false,
        internalType: "struct IDstChainPayment.PaymentPayload",
        name: "payload",
        type: "tuple",
      },
    ],
    name: "Paid",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "provider",
            type: "address",
          },
          {
            internalType: "uint64",
            name: "nonce",
            type: "uint64",
          },
          {
            internalType: "bytes32",
            name: "account",
            type: "bytes32",
          },
          {
            components: [
              {
                internalType: "enum ResourceData.ResourceType",
                name: "resourceType",
                type: "uint8",
              },
              {
                internalType: "uint256[]",
                name: "values",
                type: "uint256[]",
              },
            ],
            internalType: "struct ResourceData.Payload[]",
            name: "payloads",
            type: "tuple[]",
          },
        ],
        internalType: "struct IDstChainPayment.PaymentPayload",
        name: "payload",
        type: "tuple",
      },
    ],
    name: "pay",
    outputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract IERC20Upgradeable",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "payFromSourceChain",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDstChainPayment__factory {
  static readonly abi = _abi;
  static createInterface(): IDstChainPaymentInterface {
    return new utils.Interface(_abi) as IDstChainPaymentInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDstChainPayment {
    return new Contract(address, _abi, signerOrProvider) as IDstChainPayment;
  }
}
