/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IHostingPaymentV2,
  IHostingPaymentV2Interface,
} from "../IHostingPaymentV2";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes28",
        name: "to",
        type: "bytes28",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "level",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "bandwidth",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "storageAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "buildingTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "pricePerMonth",
            type: "uint256",
          },
          {
            internalType: "bytes28",
            name: "to",
            type: "bytes28",
          },
          {
            internalType: "bool",
            name: "isValid",
            type: "bool",
          },
        ],
        indexed: false,
        internalType: "struct IHostingCombos.Combo",
        name: "combo",
        type: "tuple",
      },
    ],
    name: "AddCombo",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes28",
        name: "to",
        type: "bytes28",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "level",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "bandwidth",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "storageAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "buildingTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "pricePerMonth",
            type: "uint256",
          },
          {
            internalType: "bytes28",
            name: "to",
            type: "bytes28",
          },
          {
            internalType: "bool",
            name: "isValid",
            type: "bool",
          },
        ],
        indexed: false,
        internalType: "struct IHostingCombos.Combo",
        name: "combo",
        type: "tuple",
      },
    ],
    name: "UpdateCombo",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "bandwidth",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "storageAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "buildingTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "pricePerMonth",
            type: "uint256",
          },
          {
            internalType: "bytes28",
            name: "to",
            type: "bytes28",
          },
          {
            internalType: "bool",
            name: "isValid",
            type: "bool",
          },
        ],
        internalType: "struct IHostingCombos.Combo",
        name: "combo",
        type: "tuple",
      },
    ],
    name: "addCombo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes28",
        name: "uuid",
        type: "bytes28",
      },
      {
        internalType: "uint256",
        name: "tokenIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "level",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expiration_",
        type: "uint256",
      },
    ],
    name: "buy",
    outputs: [
      {
        internalType: "uint256",
        name: "cost",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "comboLength",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "level",
        type: "uint256",
      },
    ],
    name: "combos",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "bandwidth",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "storageAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "buildingTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "pricePerMonth",
            type: "uint256",
          },
          {
            internalType: "bytes28",
            name: "to",
            type: "bytes28",
          },
          {
            internalType: "bool",
            name: "isValid",
            type: "bool",
          },
        ],
        internalType: "struct IHostingCombos.Combo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "level",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expiration_",
        type: "uint256",
      },
    ],
    name: "getComboCost",
    outputs: [
      {
        internalType: "uint256",
        name: "cost",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "level",
        type: "uint256",
      },
    ],
    name: "isCustom",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        internalType: "bytes28",
        name: "uuid",
        type: "bytes28",
      },
      {
        internalType: "uint256",
        name: "tokenIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "expiration_",
        type: "uint256",
      },
    ],
    name: "renew",
    outputs: [
      {
        internalType: "uint256",
        name: "cost",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "tokenLength",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "tokens",
    outputs: [
      {
        internalType: "contract IERC20",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "level",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "bandwidth",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "storageAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "buildingTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "pricePerMonth",
            type: "uint256",
          },
          {
            internalType: "bytes28",
            name: "to",
            type: "bytes28",
          },
          {
            internalType: "bool",
            name: "isValid",
            type: "bool",
          },
        ],
        internalType: "struct IHostingCombos.Combo",
        name: "combo",
        type: "tuple",
      },
    ],
    name: "updateCombo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes28",
        name: "uuid",
        type: "bytes28",
      },
      {
        internalType: "uint256",
        name: "tokenIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "level",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "moreExpiration",
        type: "uint256",
      },
    ],
    name: "upgrade",
    outputs: [
      {
        internalType: "uint256",
        name: "cost",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IHostingPaymentV2__factory {
  static readonly abi = _abi;
  static createInterface(): IHostingPaymentV2Interface {
    return new utils.Interface(_abi) as IHostingPaymentV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHostingPaymentV2 {
    return new Contract(address, _abi, signerOrProvider) as IHostingPaymentV2;
  }
}
